### ISSUE TITLE
Dark mode always renders first on page reload

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#185] opened 2022-09-06 01:30 UTC
![Kapture 2022-09-06 at 11 29 55](https://user-images.githubusercontent.com/52020637/188528149-85051258-2f24-4c73-9960-73aa07f98b45.gif)

**Comment by endigo9740** [comment] 2022-09-06 03:32
Yeah I'm aware of this one. It's a bit of a red herring and not actually a new issue. Rather, it was introduced when we dropped the SvelteKit-specific lifecycle event in the LightSwitch in the prior release. The `onMount` event we use now allows the LightSwitch to work in Vite/Astro, but appears fire later in the overall startup lifecycle. However, what's interesting is (to my knowledge) it really only affects the local dev server version of the doc site.

If you view the production Skeleton site you'll notice the issue isn't present, or at least less noticeable (for me in Chrome). This may have something to do with the face that once you interact with the LightSwitch, it switches from the default "system mode" and instead persists light/dark mode via local storage. However, if you can find a way to reproduce the issue on a built/production site please let me know! If not we can chalk it up to a doc-only issue and close this ticket.

Btw, on the doc site we can either default to light with a flash of dark, or dark with a flash of light based on our default setting of the `.dark` class on the `<html>` element. I figured a flash of dark would be a bit less jarring than the opposite!

**Comment by endigo9740** [comment] 2022-09-06 15:58
After discussing on Discord it sounds like we're on the same page here. Should only be a dev server issue. I'm going to close now but don't mind us revisiting in the future though.

**Closed by endigo9740** 2022-09-06 15:58 UTC

**Comment by luke-hagar-sp** [comment] 2022-09-07 12:23
I'm not sure if it's maybe my browser or not but I absolutely get this on the published Prod page
it's just faster

**Comment by luke-hagar-sp** [comment] 2022-09-07 12:23
IMO there may be a solution here, I'll dig into it

**Comment by luke-hagar-sp** [comment] 2022-09-07 12:59
I take it back, its so brief in prod I think I agree its not worth effort right now
