### ISSUE TITLE
Skeleton website update broke my local storage 

### ISSUE THREAD

**Issue by KevM** [Brain-Bones/skeleton#486] opened 2022-11-01 18:34 UTC
### Link to the Page

https://www.skeleton.dev/docs/features

### Describe the Issue

My browser had a theme selected. After today's (2020/11/01) release I went to check out the new docs and could not select any tabs but the `docs` tab. 
* I opened an incognito window and it did not have the problem. 🟢
* I removed cookies. No luck. 🛑
* I removed local storage keys. Which fixed the problem 🟢

It looks like one of the local storage keys was preventing the tab from switching. Sorry I should have tried the keys one at a time. 🐲

**Comment by endigo9740** [comment] 2022-11-01 18:39
@KevM Hey thanks for the heads up. Strangely we didn't change any of the local storage values, so I'm not sure what's up. We had a couple other folks mention something similar on Discord. One user mentioned the following helped them:

![image](https://user-images.githubusercontent.com/1509726/199312017-ccaaa7e6-c848-4b8b-b732-be4241ee630c.png)

> Clearing the local and sessions storage got it working for me!

I'd recommend giving that a try and reporting back if it helps.

**Comment by KevM** [comment] 2022-11-01 18:51
I wiped my local storage keys and it fixed the problem for me. Thanks.

**Comment by endigo9740** [comment] 2022-11-01 18:56
Very odd, I wish I knew what was up. Sorry about that! Let us know if we can help with anything else! I'll go ahead and close this out since it sounds like the issue is resolved.

**Closed by endigo9740** 2022-11-01 18:56 UTC
Labels: bug, documentation
